### ISSUE TITLE
Should easycart enforce integer type on quantities?

### ISSUE THREAD

**Issue by n3storm** [nevimov/django-easycart#1]
I am using intercooler.js to make post request to easycart and looks like not always quantities are stored as integers so when computing totals easycart fails saying Decimal cannot be multiplied by sequence (unicode). I fixed it by converting to integer.

Are you interested in a pull request?

Thanks for your project.

Cheers,
Néstor

**Comment by nevimov** [comment]
Hi. Thanks for the feedback. I'm a bit busy right now. I'll take a look at the issue and your pull request at the beginning of the next week.

**Comment by nevimov** [comment]
Hmmm... That's strange. Both BaseItem.__init__() and BaseCart.add() call _clean_quantity() to convert the quantities to integer values. Can you provide more information on how to reproduce the issue?
You're welcome to open the pull request.

**Comment by n3storm** [comment]
Hi nevimov, thanks for following up this issue.

I think cart should not allow negative values by just ignoring them, but not rising an exception. Also, setting 0 quantity should mean delete. Would you like me to open another issue to discuss this?

**Comment by nevimov** [comment]
Hi. Yes, open another issue.
