### ISSUE TITLE
Data validation should not raise errors, just ignore.

### ISSUE THREAD

**Issue by n3storm** [nevimov/django-easycart#3]
I think cart should not allow negative values, just ignore them, but not raise an exception.
Also, setting 0 quantity should mean delete or nothing.

Maybe a EASYCART_DEBUG setting True will raise this issues and else just ignore them.

We are dealing with anonymous user input, and maybe robots, scrappers in the wild so I think easycart should not be easily breakable by default (no pun intended)

(this is not a priority as I am validating input in my views)

Thanks for your software.

**Comment by nevimov** [comment]
I see your point. I'll need some time to think about it.

**Comment by n3storm** [comment]
I think of a cart like a form. If form doesn't validate it shows errors, but dosen't raise exceptions.
(just in case it helps you taking decission)

**Comment by nevimov** [comment]
Thanks for valuable advice. I'll fix this and related issues in the next release, which should be ready in a couple of days.

**Comment by nevimov** [comment]
Done. Check out [CHANGELOG]. The constructive criticism is welcomed.

[CHANGELOG]: https://github.com/nevimov/django-easycart/blob/master/CHANGELOG.rst#030----2016-07-02
