### ISSUE TITLE
Should/Could i access the request from the cart item object ?

### ISSUE THREAD

**Issue by altimore** [nevimov/django-easycart#4]
Hello, 

I'm writing a small shop website and i'm using your project, it is very nice but i'm struggling with a small use case.
I would like to change the price depending on who is connected and from which country.
These informations are in the session.
I can access the session from the easycart.cart.BaseCart.request but not from the BaseItem one.

My purpose would be to override the easycart.cart.BaseItem.get_price() method to output the right amount depending on the parameters in session.

Thanks, 

Alti.

**Comment by nevimov** [comment]
Hi, Alti. Glad you like the app.
I've added ability to access the cart from the item class through attribute 'cart'.
Update the app and try to use 'item.cart.request' (suppose 'item' is an instance of your cart item class).
Let me know, if it solves your problem, so I can close this issue.

**Comment by altimore** [comment]
Hello, 

Thanks for answering so fast, i tried the new version and everything works as intended now.

Regards, 

Alti
