### ISSUE TITLE
No ajax cart-list view ?

### ISSUE THREAD

**Issue by olivierdalang** [nevimov/django-easycart#5]
Hi !

I think an ajax cart-list view should be provided, returning the cart content without doing any change.

Great tool ! Thanks !

**Comment by nevimov** [comment]
Hi! It's quite easy to create such a view yourself. There's no need to add new methods to the cart class.
For example:
```python
from django.views.generic import View

class ShowItems(View):

    def get(self, request):
        return Cart(request).encode()
```
Where `Cart` is your subclass of the `easycart.BaseCart` class.

I thought about adding it a long time ago, when first writing the app, but
haven't found any valid use case for it. Could you provide one?
