### ISSUE TITLE
Flexible update view

### ISSUE THREAD

**Issue by olivierdalang** [nevimov/django-easycart#7]
Hi !

It would be nice if there was an "UpdateItem" view (or whatever other name) that would automatically proxy to AddItem if the item doesn't exist, to RemoveItem if the quantity is set to 0, and to ChangeItemQuantity else.

Think of an UI where the user just enters the number of items in a list of products.

**Comment by olivierdalang** [comment]
Code is here (based on the other PR) : https://github.com/olivierdalang/django-easycart/compare/list-cart...olivierdalang:autoupdate-item

 I can make a PR if you like the two changes.

Let me know...

**Comment by nevimov** [comment]
Hi, I don't want to merge this code right now, but maybe I'll do it later, if there will be demand for this feature. In any case, thanks for the idea.
